import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";
import type { Dictionary, TransformedToken } from "style-dictionary/types";
import { getReferences, usesReferences } from "style-dictionary/utils";
import { tokens } from "./tokens/index.js";

// Build pipeline (M0 frontend design D3): one Style Dictionary source → a single
// `tokens.css` with :root (light) + [data-theme="dark"] + [data-density] blocks +
// reduced-motion, and a Tailwind v4 preset exposing semantic names only. Semantic tokens
// reference primitives, so they emit as `var(--primitive)` — that is what makes dark "a
// token swap only". See docs/PartA_Direction_Tokens_LOCKED.md.

// --- Naming: CSS variable name = token path joined with '-' (segments are pre-cased). ---
StyleDictionary.registerTransform({
  name: "name/erp",
  type: "name",
  transform: (token) => token.path.join("-"),
});

// --- Block classification: which selector a token lands in, and its emitted var name. ---
type Block = "root" | "dark" | "density-comfortable" | "density-compact" | "density-touch";

function classify(token: TransformedToken): { block: Block; name: string } {
  const p = token.path;
  if (p[0] === "light") return { block: "root", name: p.slice(1).join("-") };
  if (p[0] === "dark") return { block: "dark", name: p.slice(1).join("-") };
  if (p[0] === "density") {
    return { block: `density-${p[1]}` as Block, name: `density-${p.slice(2).join("-")}` };
  }
  return { block: "root", name: p.join("-") };
}

// A referenced value ("{cyan.700}") becomes `var(--cyan-700)`; a literal passes through.
function cssValue(token: TransformedToken, tokenTree: Dictionary["tokens"]): string {
  const orig: unknown = token.original?.value ?? token.value;
  if (typeof orig === "string" && usesReferences(orig)) {
    return orig.replace(/\{([^}]+)\}/g, (_match, ref: string) => {
      const name = getReferences(`{${ref}}`, tokenTree)[0]?.name;
      if (!name) throw new Error(`Unresolved token reference: {${ref}}`);
      return `var(--${name})`;
    });
  }
  return String(token.value ?? orig);
}

const BLOCK_ORDER: Block[] = ["root", "dark", "density-comfortable", "density-compact", "density-touch"];
const BLOCK_SELECTOR: Record<Block, string> = {
  root: ":root",
  dark: '[data-theme="dark"]',
  // Comfortable doubles as the attribute-less default so the app is styled before the shell
  // sets data-density.
  "density-comfortable": ':root,\n[data-density="comfortable"]',
  "density-compact": '[data-density="compact"]',
  "density-touch": '[data-density="touch"]',
};

const HEADER = `/**
 * Generated by @erp/design-tokens — do not edit by hand.
 * Source: packages/design-tokens/src/tokens/*
 * Locked values: docs/PartA_Direction_Tokens_LOCKED.md
 */\n\n`;

export function renderCss(dictionary: Dictionary): string {
  const blocks = new Map<Block, string[]>();
  for (const token of dictionary.allTokens) {
    const { block, name } = classify(token);
    const lines = blocks.get(block) ?? [];
    lines.push(`  --${name}: ${cssValue(token, dictionary.tokens)};`);
    blocks.set(block, lines);
  }

  let css = HEADER;
  for (const block of BLOCK_ORDER) {
    const lines = blocks.get(block);
    if (!lines?.length) continue;
    css += `${BLOCK_SELECTOR[block]} {\n${lines.join("\n")}\n}\n\n`;
  }
  // Motion collapses to 0 under reduced-motion (§5.4).
  css += `@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-fast: 0ms;
    --motion-base: 0ms;
    --motion-slow: 0ms;
  }
}\n`;
  return css;
}

// Tailwind v4 `@theme inline` preset. Semantic names only — no primitive is exposed, which
// is half the "semantic-only consumption" enforcement (the lint ban is the other half).
// `inline` makes utilities reference the runtime var directly, so theme/density stay live.
export function renderTailwindCss(dictionary: Dictionary): string {
  const lines: string[] = [];
  const add = (themeKey: string, cssVar: string) => lines.push(`  ${themeKey}: var(--${cssVar});`);

  for (const token of dictionary.allTokens) {
    const p = token.path;
    if (p[0] === "light" && p[1] === "color") add(`--color-${p.slice(2).join("-")}`, `color-${p.slice(2).join("-")}`);
    else if (p[0] === "light" && p[1] === "chip") add(`--color-chip-${p.slice(2).join("-")}`, `chip-${p.slice(2).join("-")}`);
    else if (p[0] === "radius") add(`--radius-${p[1]}`, `radius-${p[1]}`);
    else if (p[0] === "font") add(`--font-${p[1]}`, `font-${p[1]}`);
    else if (p[0] === "text" && p[2] === "size") add(`--text-${p[1]}`, `text-${p[1]}-size`);
    else if (p[0] === "elevation") add(`--shadow-${p[1]}`, `elevation-${p[1]}`);
    else if (p[0] === "bp") add(`--breakpoint-${p[1]}`, `bp-${p[1]}`);
    else if (p[0] === "ease") add(`--ease-${p[1]}`, `ease-${p[1]}`);
    // Overrides Tailwind's built-in leading-* scale with the locked Thai-safe values (M0 §7).
    else if (p[0] === "leading") add(`--leading-${p[1]}`, `leading-${p[1]}`);
  }

  return `/* Generated by @erp/design-tokens — Tailwind v4 preset (semantic names only). */\n@theme inline {\n${lines.join("\n")}\n}\n`;
}

// JS compat shim for tooling that still expects a JS preset object.
export function renderTailwindJs(dictionary: Dictionary): string {
  const colors: Record<string, string> = {};
  const borderRadius: Record<string, string> = {};
  const fontFamily: Record<string, string> = {};
  const fontSize: Record<string, string> = {};
  const boxShadow: Record<string, string> = {};
  const screens: Record<string, string> = {};

  for (const token of dictionary.allTokens) {
    const [group, sub] = token.path;
    const rest = token.path.slice(2).join("-");
    if (group === "light" && sub === "color") colors[rest] = `var(--color-${rest})`;
    else if (group === "light" && sub === "chip") colors[`chip-${rest}`] = `var(--chip-${rest})`;
    else if (group === "radius" && sub) borderRadius[sub] = `var(--radius-${sub})`;
    else if (group === "font" && sub) fontFamily[sub] = `var(--font-${sub})`;
    else if (group === "text" && sub && token.path[2] === "size") fontSize[sub] = `var(--text-${sub}-size)`;
    else if (group === "elevation" && sub) boxShadow[sub] = `var(--elevation-${sub})`;
    else if (group === "bp" && sub) screens[sub] = `var(--bp-${sub})`;
  }

  const preset = { theme: { extend: { colors, borderRadius, fontFamily, fontSize, boxShadow, screens } } };
  return `/* Generated by @erp/design-tokens — Tailwind JS preset shim (semantic names only). */\nexport default ${JSON.stringify(preset, null, 2)};\n`;
}

const TAILWIND_DTS = `/* Generated by @erp/design-tokens. */
declare const preset: {
  theme: {
    extend: {
      colors: Record<string, string>;
      borderRadius: Record<string, string>;
      fontFamily: Record<string, string>;
      fontSize: Record<string, string>;
      boxShadow: Record<string, string>;
      screens: Record<string, string>;
    };
  };
};
export default preset;
`;

// Register the file-emitting formats against the render functions above.
StyleDictionary.registerFormat({ name: "css/erp-tokens", format: ({ dictionary }) => renderCss(dictionary) });
StyleDictionary.registerFormat({ name: "tailwind/erp-preset-css", format: ({ dictionary }) => renderTailwindCss(dictionary) });
StyleDictionary.registerFormat({ name: "tailwind/erp-preset-js", format: ({ dictionary }) => renderTailwindJs(dictionary) });
StyleDictionary.registerFormat({ name: "tailwind/erp-preset-dts", format: () => TAILWIND_DTS });

function makeSd(buildPath: string): StyleDictionary {
  return new StyleDictionary({
    tokens,
    log: { verbosity: "silent" },
    platforms: {
      css: {
        transforms: ["name/erp"],
        buildPath,
        files: [
          { destination: "css/tokens.css", format: "css/erp-tokens" },
          { destination: "tailwind/preset.css", format: "tailwind/erp-preset-css" },
          { destination: "tailwind/preset.js", format: "tailwind/erp-preset-js" },
          { destination: "tailwind/preset.d.ts", format: "tailwind/erp-preset-dts" },
        ],
      },
    },
  });
}

/** Write the token artifacts to `${buildPath}/{css,tailwind}/…`. */
export async function buildTokens(buildPath = "dist/"): Promise<void> {
  await makeSd(buildPath).buildAllPlatforms();
}

/** Render every artifact in-memory (no file IO) — used by the locked-value tests. */
export async function renderAll(): Promise<{ css: string; tailwindCss: string; tailwindJs: string }> {
  const dictionary = await makeSd("dist/").getPlatformTokens("css");
  return {
    css: renderCss(dictionary),
    tailwindCss: renderTailwindCss(dictionary),
    tailwindJs: renderTailwindJs(dictionary),
  };
}

// Run as a script: `tsx src/build-tokens.ts`.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens()
    .then(() => console.log("✓ @erp/design-tokens: built dist/css/tokens.css + dist/tailwind/preset.{css,js,d.ts}"))
    .catch((error: unknown) => {
      console.error(error);
      process.exit(1);
    });
}
