-- DOWN script for 0013_tenancy_rls.sql — NOT journaled, never run by the migrator. Drops the
-- tenant_isolation policies, disables RLS, and restores 0012's transitional default-tenant
-- fallback on every tenant_id. Leaves erp_owner's BYPASSRLS in place (harmless without
-- policies). Run by hand as a superuser, then delete the 0013 row from
-- drizzle.__drizzle_migrations. Only safe while every row lives in the default tenant.
BEGIN;
DROP POLICY IF EXISTS "tenant_isolation" ON "user";
ALTER TABLE "user" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "user" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "session";
ALTER TABLE "session" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "session" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "audit_log";
ALTER TABLE "audit_log" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "audit_log" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_log" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "document_sequence";
ALTER TABLE "document_sequence" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "document_sequence" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "document_sequence" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "idempotency_key";
ALTER TABLE "idempotency_key" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "idempotency_key" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "idempotency_key" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "role";
ALTER TABLE "role" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "role" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "role" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "role_permission";
ALTER TABLE "role_permission" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "role_permission" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "role_permission" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "user_role";
ALTER TABLE "user_role" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_role" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user_role" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "role_template";
ALTER TABLE "role_template" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "role_template" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "role_template" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "item";
ALTER TABLE "item" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "item" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "item" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "sku";
ALTER TABLE "sku" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "sku" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sku" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "uom";
ALTER TABLE "uom" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "uom" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "uom" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "uom_conversion";
ALTER TABLE "uom_conversion" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "uom_conversion" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "uom_conversion" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "warehouse";
ALTER TABLE "warehouse" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "warehouse" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "warehouse" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_balance";
ALTER TABLE "stock_balance" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_balance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_balance" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_lot";
ALTER TABLE "stock_lot" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_lot" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_lot" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_movement";
ALTER TABLE "stock_movement" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_movement" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_movement" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "goods_issue";
ALTER TABLE "goods_issue" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_issue" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "goods_issue" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "goods_issue_line";
ALTER TABLE "goods_issue_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_issue_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "goods_issue_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "goods_receipt";
ALTER TABLE "goods_receipt" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "goods_receipt_line";
ALTER TABLE "goods_receipt_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "bom";
ALTER TABLE "bom" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "bom" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "bom" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "bom_line";
ALTER TABLE "bom_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "bom_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "bom_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_adjustment";
ALTER TABLE "stock_adjustment" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_adjustment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_adjustment" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_adjustment_line";
ALTER TABLE "stock_adjustment_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_adjustment_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_adjustment_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_count";
ALTER TABLE "stock_count" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_count" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_count" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "stock_count_line";
ALTER TABLE "stock_count_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_count_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_count_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "department";
ALTER TABLE "department" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "department" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "department" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "position";
ALTER TABLE "position" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "position" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "position" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "employee";
ALTER TABLE "employee" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "employee" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "employee" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "employee_document";
ALTER TABLE "employee_document" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "employee_document" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_document" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "reporting_line";
ALTER TABLE "reporting_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "reporting_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "reporting_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "employee_pay_component";
ALTER TABLE "employee_pay_component" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "employee_pay_component" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_pay_component" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "pay_component";
ALTER TABLE "pay_component" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "pay_component" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "pay_component" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "salary_record";
ALTER TABLE "salary_record" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "salary_record" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "salary_record" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "attendance";
ALTER TABLE "attendance" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "attendance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "attendance" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "ot_request";
ALTER TABLE "ot_request" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "ot_request" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ot_request" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "cash_advance";
ALTER TABLE "cash_advance" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "cash_advance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cash_advance" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "payroll_run";
ALTER TABLE "payroll_run" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "payroll_run" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "payroll_run" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "payslip";
ALTER TABLE "payslip" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "payslip" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "payslip" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "advance_policy";
ALTER TABLE "advance_policy" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "advance_policy" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "advance_policy" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "ot_rate";
ALTER TABLE "ot_rate" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "ot_rate" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ot_rate" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "sso_config";
ALTER TABLE "sso_config" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_config" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_config" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "tax_bracket";
ALTER TABLE "tax_bracket" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "tax_bracket" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "tax_bracket" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "routing_step";
ALTER TABLE "routing_step" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "routing_step" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "routing_step" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "routing_template";
ALTER TABLE "routing_template" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "routing_template" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "routing_template" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "work_order";
ALTER TABLE "work_order" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "work_order" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "work_order" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "work_order_step";
ALTER TABLE "work_order_step" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "work_order_step" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "work_order_step" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "defect";
ALTER TABLE "defect" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "defect" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "defect" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "production_scan";
ALTER TABLE "production_scan" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "production_scan" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "production_scan" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "subcontract";
ALTER TABLE "subcontract" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "subcontract" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "subcontract" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "customer";
ALTER TABLE "customer" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "customer" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "customer" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "quotation";
ALTER TABLE "quotation" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "quotation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "quotation" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "invoice";
ALTER TABLE "invoice" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "invoice" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "doc_line";
ALTER TABLE "doc_line" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "doc_line" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "doc_line" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "payment";
ALTER TABLE "payment" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "payment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "payment" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "receipt_tax_invoice";
ALTER TABLE "receipt_tax_invoice" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "receipt_tax_invoice" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "receipt_tax_invoice" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "wht_certificate";
ALTER TABLE "wht_certificate" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "wht_certificate" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "wht_certificate" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "document_template";
ALTER TABLE "document_template" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "document_template" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "document_template" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
DROP POLICY IF EXISTS "tenant_isolation" ON "report_schedule";
ALTER TABLE "report_schedule" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "report_schedule" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "report_schedule" ALTER COLUMN "tenant_id" SET DEFAULT coalesce(nullif(current_setting('app.tenant_id', true), '')::uuid, '00000000-0000-4000-8000-000000000001'::uuid);
COMMIT;
